name: Build Bun Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Compile to binary
        run: |
          bun build src/index.ts --compile --outfile ./dist/t${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary-${{ matrix.os }}
          path: ./dist/*
